package com.shop.ecommerce.model;

import com.shop.ecommerce.model.UserSegment;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;       // for date and time
import java.util.List;
import java.util.ArrayList;

@Entity
@Table(name = "users")
public class User {

    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @Setter
    @Getter
    @Column(name = "user_name", nullable = false, unique = true)
    private String userName;
    
    @Setter
    @Getter
    @Column(nullable = false, unique = true)
    private String email;
    
    @Setter
    @Getter
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;
    
    @Setter
    @Getter
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Setter
    @Getter
    @Column(name = "is_guest")
    private boolean isGuest;

    @Setter
    @Getter
    @Enumerated(EnumType.STRING)
    @Column(name = "segment")
    private UserSegment segment;

    @Setter
    @Getter
    @Column(name = "last_activity")
    private LocalDateTime lastActivity;

    @Setter
    @Getter
    @Column(name = "last_classified_at")
    private LocalDateTime lastClassifiedAt;

    @Setter
    @Getter
    @Column(name = "event_counter")
    private int eventCounter;

    @Setter
    @Getter
    @Column(name = "ml_category")
    private String mlCategory;  // ML category from Phase 1 (e.g., "high_value", "active_browser", etc.)

    // table for user search history to know how many times a user searched for keyword (example : "laptop : 4 times")
    @Setter
    @Getter
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<UserSearchHistory> searchHistory;

    @Setter
    @Getter
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<UserViewHistory> viewHistory;

    @Setter
    @Getter
    @ElementCollection
    @CollectionTable(name = "user_purchase_history", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "product_id")
    private List<Integer> purchaseHistory;
    
    @Setter
    @Getter
    @ElementCollection
    @CollectionTable(name = "user_wishlist", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "product_id")
    private List<Integer> wishList;
    
    @Setter
    @Getter
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<CartItem> cartItems;

    @Getter
    @Setter
    @Column(name = "wallet_balance", nullable = false)
    private double walletBalance = 0.0;

    /** Stripe Customer ID – required for reusing saved payment methods */
    @Getter
    @Setter
    @Column(name = "stripe_customer_id", unique = true)
    private String stripeCustomerId;

    // Default constructor required by JPA
    public User() {
        this.searchHistory = new ArrayList<UserSearchHistory>();
        this.viewHistory = new ArrayList<UserViewHistory>();
        this.purchaseHistory = new ArrayList<Integer>();
        this.wishList = new ArrayList<Integer>();
        this.cartItems = new ArrayList<CartItem>();
    }


    // removed id in constructor (generated by database)
    // User Constructor
    public User(String userName, String email, String passwordHash, LocalDateTime createdAt) {
        this.userName = userName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.createdAt = LocalDateTime.now();
        this.isGuest = true;
        this.searchHistory = new ArrayList<UserSearchHistory>();
        this.viewHistory = new ArrayList<UserViewHistory>();
        this.purchaseHistory = new ArrayList<Integer>();
        this.wishList = new ArrayList<Integer>();
        this.cartItems = new ArrayList<CartItem>();
        this.segment = UserSegment.UNCLASSIFIED;
        this.eventCounter = 0;
        this.lastClassifiedAt = null;
        this.lastActivity = LocalDateTime.now();
    }

}